use chrono::{DateTime, Utc};
use reqwest::Client;
use serde::{Deserialize, Serialize};
use tracing::{info, warn};

use crate::error::SyncError;

// ── Trash Entry ──────────────────────────────────────────────────────────────

/// Metadata for a soft-deleted file. The actual R2 operations (copy to
/// `_trash/` prefix, delete original) are performed via presigned URLs
/// generated by Convex.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrashEntry {
    /// The original R2 object key (e.g. `_objects/{blake3-hash}.wav`).
    pub original_key: String,
    /// The trash R2 object key (e.g. `_trash/{session-uuid}/{blake3-hash}.wav`).
    pub trash_key: String,
    /// When the soft-delete was performed.
    pub deleted_at: DateTime<Utc>,
    /// The session this file belonged to.
    pub session_id: String,
}

// ── Soft-Delete via Presigned URLs ───────────────────────────────────────────

/// Perform a soft-delete by copying an object to the `_trash/` prefix and then
/// deleting the original. Both operations use presigned URLs supplied by
/// Convex so the client never holds raw R2 credentials.
///
/// **Flow:**
/// 1. PUT to `presigned_copy_url` — R2 copies the object to `_trash/{session}/{hash}`
/// 2. DELETE to `presigned_delete_url` — R2 removes the original object
///
/// If the copy succeeds but the delete fails, the object exists in both
/// locations — acceptable because the trash cleanup job will still work and
/// the original can be re-deleted later.
pub async fn trash_file(
    client: &Client,
    presigned_copy_url: &str,
    presigned_delete_url: &str,
) -> Result<(), SyncError> {
    // Step 1: Copy object to trash prefix via presigned PUT.
    info!("Soft-delete: copying object to trash prefix");
    let copy_response = client.put(presigned_copy_url).send().await?;

    if !copy_response.status().is_success() {
        let status = copy_response.status();
        let body_text = copy_response.text().await.unwrap_or_default();
        return Err(SyncError::R2Upload {
            key: "trash-copy".to_string(),
            source: format!("Copy to trash failed — HTTP {status}: {body_text}").into(),
        });
    }

    info!("Soft-delete: copy to trash succeeded, deleting original");

    // Step 2: Delete the original object via presigned DELETE.
    let delete_response = client.delete(presigned_delete_url).send().await?;

    if !delete_response.status().is_success() {
        let status = delete_response.status();
        let body_text = delete_response.text().await.unwrap_or_default();
        // Log but don't fail — object is safely in trash. The original can be
        // cleaned up by a retry or the periodic trash reconciliation.
        warn!(
            "Soft-delete: original deletion failed — HTTP {status}: {body_text}. \
             Object is in trash; original will be cleaned up on next reconciliation."
        );
        return Err(SyncError::R2Upload {
            key: "trash-delete-original".to_string(),
            source: format!(
                "Delete original after trash copy failed — HTTP {status}: {body_text}"
            )
            .into(),
        });
    }

    info!("Soft-delete: complete (copied to trash and deleted original)");
    Ok(())
}

/// Perform soft-delete for multiple objects in sequence. Returns a list of
/// entries that were successfully trashed and a list of errors. This is a
/// best-effort batch operation — individual failures do not abort the batch.
pub async fn trash_files(
    client: &Client,
    operations: Vec<TrashOperation>,
) -> (Vec<TrashEntry>, Vec<SyncError>) {
    let mut successes = Vec::new();
    let mut errors = Vec::new();

    for op in operations {
        match trash_file(client, &op.presigned_copy_url, &op.presigned_delete_url).await {
            Ok(()) => {
                successes.push(TrashEntry {
                    original_key: op.original_key,
                    trash_key: op.trash_key,
                    deleted_at: Utc::now(),
                    session_id: op.session_id,
                });
            }
            Err(e) => {
                warn!(
                    "Failed to trash {}: {}",
                    op.original_key, e
                );
                errors.push(e);
            }
        }
    }

    (successes, errors)
}

// ── Trash Operation Input ────────────────────────────────────────────────────

/// Input for a single trash operation, carrying the presigned URLs and
/// metadata needed to construct the `TrashEntry` on success.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrashOperation {
    pub original_key: String,
    pub trash_key: String,
    pub session_id: String,
    pub presigned_copy_url: String,
    pub presigned_delete_url: String,
}
